import Building from '../../../assets/schools/isatu_building.jpg';
import Logo from '../../../assets/schools/isatu_logo.png';
// import Location from '../../../assets/schools/';

const data = {
  id: 6,
  name: 'Iloilo Science and Technology University',
  thumbnail: Logo,
  image: Building,
  motto: 'Universitas Technologiae et Scientiarum Iloilensis',
  // location: Location,
  courses: [
    {
      id: 0,
      name: 'BS IN AUTOMOTIVE TECHNOLOGY',
      description: `A 4-YEAR DEGREE IS THE MINIMUM QUALIFICATION FOR MOST AUTOMOTIVE ENGINEERING POSITIONS. UNDERGRADUATE PROGRAMS IN THIS FIELD ARE MOST COMMONLY OFFERED IN AUTOMOTIVE ENGINEERING TECHNOLOGY, WHICH CAN COVER THE BASIC PRINCIPLES OF ENGINEERING ALONG WITH MODERN VEHICLE DESIGN REQUIREMENTS IN TERMS OF SAFETY, FUEL ECONOMY AND INDUSTRIAL MANUFACTURING. WHILE MASTER'S DEGREE PROGRAMS IN AUTOMOTIVE ENGINEERING ARE AVAILABLE, AUTOMOTIVE ENGINEERING IS A COMPLEX AND INTERDISCIPLINARY FIELD, SO STUDENTS MAY ALSO FIND RELEVANT COURSEWORK THROUGH GRADUATE PROGRAMS IN ELECTRICAL ENGINEERING, ENVIRONMENTAL ENGINEERING AND MECHANICAL ENGINEERING.`
    },
    {
      id: 1,
      name: 'BS IN ELECTRICAL TECHNOLOGY',
      description: `The BS in Information Technology major in Electrical Technology program provides a comprehensive knowledge on the theories and concepts of data, systems and technology.
      It aims to train students to acquire skills in creating computer based software applications necessary for any business and industry. It seeks to produce graduates who are competent and ready to work in the fields of business and computer technology.`
    },
    {
      id: 2,
      name: 'BS IN ELECTRONICS TECHNOLOGY',
      description: `The Bachelor of Science (BS) degree with an area of study in Electrical Technology is designed for electricians and electrical power or machinery workers. The program enables mid-career adults in the electrical industry meet their educational and professional needs while completing a baccalaureate degree.`
    },
    {
      id: 3,
      name: 'BS IN HOTEL AND RESTAURANT TECHNOLOGY',
      description: `BACHELOR DEGREES IN HOTEL AND RESTAURANT MANAGEMENT ARE 4-YEAR PROGRAMS THAT OFFER THE MANAGEMENT SKILLS, FINANCIAL KNOWLEDGE AND PROBLEM-SOLVING ABILITIES REQUIRED TO OVERSEE A STAFF AND GUARANTEE SMOOTH OPERATIONS AT A TOURISM-RELATED ESTABLISHMENT. MOST PROGRAMS ALSO REQUIRE DEGREE CANDIDATES TO COMPLETE AN INTERNSHIP OR WORK-STUDY EXPERIENCE AT A LOCAL LODGING OR FOOD SERVICE FACILITY.`
    },
    {
      id: 4,
      name:
        'BS IN INDUSTRIAL EDUCATION MAJOR IN ARCHITECHTURAL DRAFTING TECHNOLOGY',
      description: `THE BACHELOR OF SCIENCE IN INDUSTRIAL EDUCATION (BSIE) IS A FOUR-YEAR LADDERIZED ACADEMIC PROGRAM DESIGNED TO PREPARE STUDENTS FOR TEACHING TECHNICAL COURSES IN SECONDARY AND COLLEGE LEVELS, INCLUDING VOCATIONAL SCHOOLS. THE PROGRAM COVERS A VARIETY OF TECHNICAL AND TECHNOLOGICAL SUBJECTS, INCLUDING AUTOMOTIVE, CIVIL, DRAFTING, ELECTRICAL, ELECTRONICS, FOOD AND GARMENTS TECHNOLOGY, COMPUTER AND REFRIGERATION AND AIR-CONDITIONING. THE PROGRAM AIMS TO STRENGTHEN THE STUDENTS’ KNOWLEDGE OF TECHNICAL SKILLS AND EFFECTIVE TEACHER EDUCATION. BSIE IS A LADDERIZED PROGRAM, MEANING THAT THE STUDENTS WHO SUCCESSFULLY COMPLETE EACH YEAR LEVEL AND PASS THE TESDA COMPETENCY ASSESSMENT ARE ISSUED THE NATIONAL CERTIFICATE (NC) OF THAT PARTICULAR LEVEL.
      AN ARCHITECTURAL DRAFTING TECHNOLOGY PROGRAM WILL INTRODUCE YOU TO THE FIELD OF DRAFTING. YOU'LL LEARN THE ESSENTIALS OF HAND-DRAFTING, SUCH AS SKETCHING, LETTERING AND USING DRAFTING TOOLS. YOU'LL ALSO SPEND SIGNIFICANT TIME LEARNING TO USE COMPUTER-AIDED DESIGN (CAD) TOOLS. IN MUCH OF THE DRAFTING INDUSTRY, CAD IS THE STANDARD METHOD FOR CREATING ARCHITECTURAL DRAWINGS. THEREFORE, IT WILL BE IMPORTANT FOR YOU TO MASTER THE DRAWING, EDITING, LAYERING AND OTHER ASPECTS OF THIS SOFTWARE.`
    },
    {
      id: 5,
      name: 'BS IN INDUSTRIAL EDUCATION MAJOR IN ELECTRICAL TECHNOLOGY',
      description: `THE BACHELOR OF SCIENCE IN INDUSTRIAL EDUCATION (BSIE) IS A FOUR-YEAR LADDERIZED ACADEMIC PROGRAM DESIGNED TO PREPARE STUDENTS FOR TEACHING TECHNICAL COURSES IN SECONDARY AND COLLEGE LEVELS, INCLUDING VOCATIONAL SCHOOLS. THE PROGRAM COVERS A VARIETY OF TECHNICAL AND TECHNOLOGICAL SUBJECTS, INCLUDING AUTOMOTIVE, CIVIL, DRAFTING, ELECTRICAL, ELECTRONICS, FOOD AND GARMENTS TECHNOLOGY, COMPUTER AND REFRIGERATION AND AIR-CONDITIONING. THE PROGRAM AIMS TO STRENGTHEN THE STUDENTS’ KNOWLEDGE OF TECHNICAL SKILLS AND EFFECTIVE TEACHER EDUCATION. BSIE IS A LADDERIZED PROGRAM, MEANING THAT THE STUDENTS WHO SUCCESSFULLY COMPLETE EACH YEAR LEVEL AND PASS THE TESDA COMPETENCY ASSESSMENT ARE ISSUED THE NATIONAL CERTIFICATE (NC) OF THAT PARTICULAR LEVEL.`
    },
    {
      id: 6,
      name: 'BS IN INDUSTRIAL EDUCATION MAJOR IN GARMENTS',
      description: `THE BACHELOR OF SCIENCE IN INDUSTRIAL EDUCATION (BSIE) IS A FOUR-YEAR LADDERIZED ACADEMIC PROGRAM DESIGNED TO PREPARE STUDENTS FOR TEACHING TECHNICAL COURSES IN SECONDARY AND COLLEGE LEVELS, INCLUDING VOCATIONAL SCHOOLS. THE PROGRAM COVERS A VARIETY OF TECHNICAL AND TECHNOLOGICAL SUBJECTS, INCLUDING AUTOMOTIVE, CIVIL, DRAFTING, ELECTRICAL, ELECTRONICS, FOOD AND GARMENTS TECHNOLOGY, COMPUTER AND REFRIGERATION AND AIR-CONDITIONING. THE PROGRAM AIMS TO STRENGTHEN THE STUDENTS’ KNOWLEDGE OF TECHNICAL SKILLS AND EFFECTIVE TEACHER EDUCATION. BSIE IS A LADDERIZED PROGRAM, MEANING THAT THE STUDENTS WHO SUCCESSFULLY COMPLETE EACH YEAR LEVEL AND PASS THE TESDA COMPETENCY ASSESSMENT ARE ISSUED THE NATIONAL CERTIFICATE (NC) OF THAT PARTICULAR LEVEL.`
    },
    {
      id: 7,
      name: 'BS IN INDUSTRIAL TECHNOLOGY',
      description: `The Bachelor of Science in Industrial Technology is a four-year degree program designed to equip students with the basic principles and procedures of shop training and technology repair works. They also learn about the operation and maintenance of technical systems and equipment used in mechanical design and construction technology.  The program provides students with skills in manufacturing, quality assurance and control, and operations management.`
    },
    {
      id: 8,
      name: 'BACHELOR OF ELEMENTARY EDUCATION',
      description: `THE BACHELOR OF ELEMENTARY EDUCATION IS A FOUR YEAR TEACHER EDUCATION COURSE WHICH AIMS TO RESPOND TO THE DEMANDS FOR QUALITY AND COMPETENT ELEMENTARY TEACHERS IN THE REGION. GRADUATES OF THIS PROGRAM ARE EXPECTED TO POSSESS NECESSARY COMPETENCE AND APPROPRIATE METHODOLOGIES TO BE USED IN THE TEACHING AND LEARNING PROCESS AND ESPECIALLY ON THE APPROPRIATE USE OF EVALUATION INSTRUMENTS. FURTHER, IT ALSO HELPS TO DEVELOP A VALUE AND CIVIC-ORIENTED GRADUATES.`
    },
    {
      id: 9,
      name: 'BACHELOR OF SECONDARY EDUCATION',
      description: `BACHELOR OF SECONDARY EDUCATION (BSED) IS A FOUR YEAR DEGREE PROGRAM DESIGNED TO PREPARE STUDENTS FOR BECOMING HIGH SCHOOL TEACHERS. THE PROGRAM COMBINES BOTH THEORY AND PRACTICE IN ORDER TO TEACH STUDENTS THE NECESSARY KNOWLEDGE AND SKILLS A HIGH SCHOOL TEACHER NEEDS. THE PROGRAM AIMS TO PRODUCE COMPETENT TEACHERS WHO PROVIDE A CONDUCIVE LEARNING EXPERIENCE TO THEIR STUDENTS.`
    },
    {
      id: 10,
      name: 'BS IN INDUSTIAL EDUCATION',
      description: `The Bachelor of Science in Industrial Technology is a four-year degree program designed to equip students with the basic principles and procedures of shop training and technology repair works. They also learn about the operation and maintenance of technical systems and equipment used in mechanical design and construction technology.  The program provides students with skills in manufacturing, quality assurance and control, and operations management.`
    },
    {
      id: 11,
      name: 'BS IN ELECTRICAL ENGINEERING',
      description: `THE BACHELOR OF SCIENCE IN ELECTRICAL ENGINEERING DEALS WITH THE GENERATION, TRANSMISSION, DISTRIBUTION, AND UTILIZATION OF ELECTRICITY. IT ALSO DEALS WITH THE DESIGN, OPERATION AND PROTECTION, MAINTENANCE AND ECONOMICS OF ELECTRICAL SYSTEMS WITH EMPHASIS ON ETHICAL VALUES TO HARNESS ECONOMICALLY AND SAFELY THE MATERIALS AND FORCES OF NATURE FOR THE BENEFIT OF SOCIETY AND THE ENVIRONMENT.`
    },
    {
      id: 12,
      name: 'BS IN ELECTRONICS ENGINEERING',
      description: `THE BACHELOR OF SCIENCE IN ELECTRONICS AND COMMUNICATIONS ENGINEERING (BS ECE), ALSO KNOWN AS BACHELOR OF SCIENCE IN ELECTRONICS ENGINEERING, IS A FIVE-YEAR COLLEGE PROGRAM THAT FOCUSES ON THE CONCEPTUALIZATION, DESIGN, AND DEVELOPMENT OF ELECTRONIC, COMPUTER AND COMMUNICATION PRODUCTS, SYSTEMS, SERVICES AND PROCESSES. ITS CURRICULUM IS BUILT AROUND A STRONG BASIC CORE OF MATHEMATICS, PHYSICS, AND ENGINEERING PROVIDES TEACHING AND TRAINING ACTIVITIES IN THE CLASSROOM AND IN THE LABORATORY EXERCISES.`
    },
    {
      id: 13,
      name: 'BS IN MECHANICAL ENGINEERING',
      description: `The Bachelor of Science in Mechanical Engineering  is a five-year program that deals with the design, development, installation, operation, and maintenance of machinery, engines, and structures used in industrial, biomedical, instrumentation and transportation systems. The program discusses the study of the conversion of thermal and chemical energy into mechanical work through engines and power plants while teaching students the proper utilization of these energies, forces, and structures to successfully perform a variety of tasks.`
    },
    {
      id: 14,
      name: 'BS IN COMPUTER SCIENCE',
      description: `THE BACHELOR IN COMPUTER SICENCE IS THE PROGRAM CENTERS ON THE SYSTEMATIC STUDY OF COMPUTING CONCEPTS, THEORIES AND COMPUTATION. THE BODY OF KNOWLEDGE RESULTING FROM THIS DISCIPLINE CONTAINS THEORIES FOR UNDERSTANDING COMPUTING SYSTEMS AND METHODS; DESIGN METHODOLOGY, ALGORITHMS, AND TOOLS; METHODS FOR TESTING OF CONCEPTS; METHODS OF ANALYSIS AND VERIFICATION; AND KNOWLEDGE PRESENTATION AND IMPLEMENTATION.
      THE PROGRAM AIMS TO:
      PROVIDE QUALITY, COMPETENT COMPUTER SCIENCE GRADUATE THAT CAN MEET THE NEEDS OF INDUSTRY AND SOCIETY;
      PRODUCE GRADUATES WHO CAN RESPOND TO THE CHALLENGE OF A GLOBALLY COMPETITIVE INFORMATION AGE;
      PRODUCE AN EFFECTIVE EDUCATION IN COMPUTER SCIENCE DISCIPLINE, PRINCIPLES AND PRACTICES;
      PROVIDE A SOLID UNDERSTANDING OF CONCEPTS, THEORIES AND SKILLS FUNDAMENTAL TO THE DISCIPLINE OF COMPUTER SCIENCE AS WELL AS BUSINESS ANALYTIC AND SERVICE CULTURE.
      PROMOTE RESEARCH, MANAGEMENT, SCIENTIFIC STUDIES AND LEADERSHIP IN THE FIELD OF COMPUTER SCIENCE;
      PROVIDE THE KEYSTONE FOR TODAY’S COMPUTER APPLICATIONS AS WELL AS THE FOUNDATION OF WHICH TOMORROW’S APPLICATION WILL BE BASED;
      PROVIDE LOW-COST, QUALITY EDUCATION THAT WILL MEET THE DEMANDS OF THE IT INDUSTRY; AND
      PREPARE STUDENTS TO BECOME GOOD LEADERS AND RESPONSIVE MEMBERS OF THE SOCIETY.
      `
    },
    {
      id: 15,
      name: 'BS IN INFORMATION SYSTEMS',
      description: `THE BACHELOR OF SCIENCE IN INFORMATION SYSTEMS (BS IS) IS A FOUR-YEAR DEGREE PROGRAM THAT DEALS WITH THE DESIGN AND IMPLEMENTATION OF SOLUTIONS THAT INTEGRATE INFORMATION TECHNOLOGY WITH BUSINESS PROCESSES. THE PROGRAM TEACHES STUDENTS ABOUT HARDWARE AND SOFTWARE APPLICATIONS AND HOW THEY CAN USE THEM TO COLLECT, FILTER, PROCESS, CREATE AND DISTRIBUTE DATA. IT ALSO FOCUSES ON THE DESIGN, DEVELOPMENT AND IMPLEMENTATION OF INFORMATION AND COMMUNICATIONS TECHNOLOGY (ICT) RESOURCES TO ENSURE THAT INFORMATION SYSTEMS APPLICATIONS CAN BE USED IN VARIOUS INDUSTRY SECTORS SUCH AS BUSINESS, EDUCATION, MEDIA AND ENTERTAINMENT, HEALTHCARE, GOVERNMENT, AND SERVICE.`
    },
    {
      id: 16,
      name: 'BS IN INFORMATION TECHNOLOGY',
      description: `The Bachelor of Science in Information Technology (BS IT) is a four-year degree program that equips students with the basic ability to conceptualize, design and implement software applications. It prepares students to be IT professionals who are able to perform installation, operation, development, maintenance, and administration of computer applications. The goal of the program is to produce information technologists who can assist individuals and organizations in solving problems using information technology techniques and processes.`
    },
    {
      id: 17,
      name: 'BS IN ARCHITECTURE',
      description: `THE BACHELOR OF SCIENCE IN ARCHITECTURE IS THE ART, SCIENCE AND PROFESSION OF PLANNING, DESIGNING AND CONSTRUCTING BUILDINGS IN THEIR TOTALITY TAKING INTO ACCOUNT THEIR ENVIRONMENT IN ACCORDANCE WITH THE PRINCIPLES OF UTILITY, STRENGTH AND BEAUTY.`
    },
    {
      id: 18,
      name: 'BACHELOR IN FASHION DESIGN AND MERCHANDISING',
      description: `THE FASHION DESIGN AND MERCHANDISING DEGREE PROGRAM FOCUSES ON DESIGN DEVELOPMENT AND PHILOSOPHIES, AS WELL AS PRODUCTION AND MARKETING PROCEDURES WITH FASHION BUSINESS AT THE CORE. THIS DEGREE PROGRAM IS FOR THOSE WHO WANT TO DESIGN CLOTHES FOR SPECIFIC MARKETS.`
    },
    {
      id: 19,
      name: 'BS IN MATHEMATICS',
      description: `The Bachelor of Science in Mathematics  is a four-year degree program designed to give students a background in mathematical modeling, scientific computing, and various modern applications of mathematics. The program covers major areas in pure mathematics exposure to mathematical applications in statistics, operation research, and actuarial science. It also teaches students the proper use of problem-solving approaches to investigate and understand mathematical content and analyze mathematical statements and construct solutions.`
    },
    {
      id: 20,
      name: 'BACHELOR OF ARTS IN COMMUNITY DEVELOPMENT',
      description: `BACHELOR OF ARTS IN COMMUNITY DEVELOPMENT IS THE PROGRAM AIMS TO PRODUCE GRADUATES WHO WILL HELP IN THE DEVELOPMENT EFFORTS IN ERADICATING POVERTY AND IN ATTAINMENT OF A BETTER LIFE FOR EACH HUMAN BEING IN AN EQUITABLE AND JUST SOCIETY. WITH THIS PROGRAM, STUDENTS WILL BE EQUIPPED WITH THE NECESSARY KNOWLEDGE, SKILLS AND ATTITUDES TO ENGAGE IN DEVELOPMENT WORK WITHIN THE CONTEXT OF PEOPLE EMPOWERMENT AND SUSTAINABLE DEVELOPMENT.
      TO FACILITATE THE DEVELOPMENT OF SOCIALLY COMMITTED, GENDER-SENSITIVE, CAPABLE, AND PRODUCTIVE DEVELOPMENT WORKERS;
      TO ADVOCATE PARTICIPATORY STRATEGIES FOR SOCIAL TRANSFORMATION AND DEVELOPMENT, INCLUDING THE REDISTRIBUTION OF ECONOMIC AND POLITICAL MEANS FOR ACHIEVING THE ASPIRATIONS OF THE MAJORITY OF THE FILIPINO PEOPLE.
      TO PROVIDE POVERTY-FOCUSED, PEOPLE CENTERED AND GENDER RESPONSIVE SERVICES IN NEED, ESPECIALLY THOSE AT RISK.
      TO RESPOND TO THE STUDENT’S ASPIRATIONS FOR EDUCATION UPLIFT THROUGH PRAXIS-ORIENTED EDUCATION THAT PREPARE THEM FOR SERVICE TO THE PEOPLE.
      TO INSTILL FILIPINO CULTURE IN TEACHING, RESEARCH AND EXTENSION TOWARD MORE RELEVANT AND ACCESSIBLE HUMAN CENTERED SUSTAINABLE AND GENDER RESPONSIVE DEVELOPMENT.
      `
    }
  ]
};

export default data;
